import type { Order } from './types';

/**
 * Shared mock orders used in demo mode across the app.
 * IDs start with "mock-" so they can be detected as non-real orders.
 */
export function isMockOrderId(id: string): boolean {
  return id.startsWith('mock-');
}

export function getMockOrderById(id: string): Order | undefined {
  return MOCK_ORDERS.find((o) => o.id === id);
}

export const MOCK_ORDERS: Order[] = [
  // ── En cours ──
  {
    id: 'mock-001-aabb-ccdd-eeff-112233445566',
    basket_id: 'b1',
    commerce_id: 'mock-commerce-1',
    user_id: 'demo',
    amount_paid: 8.99,
    status: 'paid',
    is_donation: false,
    qr_code_token: 'KSH-4829',
    created_at: new Date().toISOString(),
    baskets: {
      type: 'bassari',
      pickup_start: new Date(new Date().setHours(17, 0)).toISOString(),
      pickup_end: new Date(new Date().setHours(19, 0)).toISOString(),
      original_price: 22.0,
      sold_price: 8.99,
      description: 'Panier viande surprise du jour',
      is_donation: false,
      commerces: { name: 'Boucherie Moché', address: '12 rue Petit', city: 'Paris 19e', postal_code: '75019', logo_url: null, commerce_type: 'Boucherie' },
    },
    associations: null,
  },
  {
    id: 'mock-002-aabb-ccdd-eeff-112233445566',
    basket_id: 'b2',
    commerce_id: 'mock-commerce-2',
    user_id: 'demo',
    amount_paid: 12.50,
    status: 'ready_for_pickup',
    is_donation: false,
    qr_code_token: 'KSH-7153',
    created_at: new Date(Date.now() - 3600_000).toISOString(),
    baskets: {
      type: 'halavi',
      pickup_start: new Date(new Date().setHours(14, 0)).toISOString(),
      pickup_end: new Date(new Date().setHours(16, 0)).toISOString(),
      original_price: 28.0,
      sold_price: 12.50,
      description: 'Assortiment fromages et laitages',
      is_donation: false,
      commerces: { name: 'Boulangerie Gan Eden', address: '45 bd Voltaire', city: 'Paris 11e', postal_code: '75011', logo_url: null, commerce_type: 'Boulangerie' },
    },
    associations: null,
  },
  {
    id: 'mock-003-aabb-ccdd-eeff-112233445566',
    basket_id: 'b3',
    commerce_id: 'mock-commerce-3',
    user_id: 'demo',
    amount_paid: 15.00,
    status: 'paid',
    is_donation: false,
    qr_code_token: 'KSH-2041',
    created_at: new Date(Date.now() - 7200_000).toISOString(),
    baskets: {
      type: 'shabbat',
      pickup_start: new Date(Date.now() + 86400_000 + 36000_000).toISOString(),
      pickup_end: new Date(Date.now() + 86400_000 + 43200_000).toISOString(),
      original_price: 35.0,
      sold_price: 15.00,
      description: 'Panier Shabbat complet (hallot, vin, desserts)',
      is_donation: false,
      commerces: { name: 'Traiteur Shalom', address: '8 av Paul Valéry', city: 'Sarcelles', postal_code: '95200', logo_url: null, commerce_type: 'Traiteur' },
    },
    associations: null,
  },
  // ── Passées ──
  {
    id: 'mock-004-aabb-ccdd-eeff-112233445566',
    basket_id: 'b4',
    commerce_id: 'mock-commerce-1',
    user_id: 'demo',
    amount_paid: 9.99,
    status: 'picked_up',
    is_donation: false,
    qr_code_token: null,
    created_at: new Date(Date.now() - 86400_000 * 2).toISOString(),
    baskets: {
      type: 'bassari',
      pickup_start: new Date(Date.now() - 86400_000 * 2 + 61200_000).toISOString(),
      pickup_end: new Date(Date.now() - 86400_000 * 2 + 68400_000).toISOString(),
      original_price: 25.0,
      sold_price: 9.99,
      description: 'Panier viande du jour',
      is_donation: false,
      commerces: { name: 'Boucherie Moché', address: '12 rue Petit', city: 'Paris 19e', postal_code: '75019', logo_url: null, commerce_type: 'Boucherie' },
    },
    associations: null,
  },
  {
    id: 'mock-005-aabb-ccdd-eeff-112233445566',
    basket_id: 'b5',
    commerce_id: 'mock-commerce-2',
    user_id: 'demo',
    amount_paid: 6.50,
    status: 'picked_up',
    is_donation: false,
    qr_code_token: null,
    created_at: new Date(Date.now() - 86400_000 * 5).toISOString(),
    baskets: {
      type: 'parve',
      pickup_start: new Date(Date.now() - 86400_000 * 5 + 43200_000).toISOString(),
      pickup_end: new Date(Date.now() - 86400_000 * 5 + 50400_000).toISOString(),
      original_price: 18.0,
      sold_price: 6.50,
      description: 'Fruits, légumes et conserves',
      is_donation: false,
      commerces: { name: 'Supermarché Hatov', address: '22 rue du Gal Leclerc', city: 'Créteil', postal_code: '94000', logo_url: null, commerce_type: 'Supermarché' },
    },
    associations: null,
  },
  {
    id: 'mock-006-aabb-ccdd-eeff-112233445566',
    basket_id: 'b6',
    commerce_id: 'mock-commerce-3',
    user_id: 'demo',
    amount_paid: 11.00,
    status: 'no_show',
    is_donation: false,
    qr_code_token: null,
    created_at: new Date(Date.now() - 86400_000 * 8).toISOString(),
    baskets: {
      type: 'mix',
      pickup_start: new Date(Date.now() - 86400_000 * 8 + 57600_000).toISOString(),
      pickup_end: new Date(Date.now() - 86400_000 * 8 + 64800_000).toISOString(),
      original_price: 30.0,
      sold_price: 11.00,
      description: 'Panier mixte surprise',
      is_donation: false,
      commerces: { name: 'Épicerie Bereshit', address: '15 rue de Lévis', city: 'Paris 17e', postal_code: '75017', logo_url: null, commerce_type: 'Épicerie' },
    },
    associations: null,
  },
  {
    id: 'mock-007-aabb-ccdd-eeff-112233445566',
    basket_id: 'b7',
    commerce_id: 'mock-commerce-1',
    user_id: 'demo',
    amount_paid: 7.99,
    status: 'refunded',
    is_donation: false,
    qr_code_token: null,
    created_at: new Date(Date.now() - 86400_000 * 12).toISOString(),
    baskets: {
      type: 'halavi',
      pickup_start: new Date(Date.now() - 86400_000 * 12 + 39600_000).toISOString(),
      pickup_end: new Date(Date.now() - 86400_000 * 12 + 46800_000).toISOString(),
      original_price: 20.0,
      sold_price: 7.99,
      description: 'Produits laitiers variés',
      is_donation: false,
      commerces: { name: 'Boulangerie Gan Eden', address: '45 bd Voltaire', city: 'Paris 11e', postal_code: '75011', logo_url: null, commerce_type: 'Boulangerie' },
    },
    associations: null,
  },
  // ── Dons ──
  {
    id: 'mock-don-001-aabb-ccdd-eeff-112233',
    basket_id: 'b8',
    commerce_id: 'mock-commerce-2',
    user_id: 'demo',
    amount_paid: 5.00,
    status: 'picked_up',
    is_donation: true,
    qr_code_token: null,
    created_at: new Date(Date.now() - 86400_000 * 3).toISOString(),
    baskets: {
      type: 'bassari',
      pickup_start: new Date(Date.now() - 86400_000 * 3 + 54000_000).toISOString(),
      pickup_end: new Date(Date.now() - 86400_000 * 3 + 61200_000).toISOString(),
      original_price: 22.0,
      sold_price: 5.00,
      description: 'Panier viande offert à une association',
      is_donation: true,
      commerces: { name: 'Boucherie Moché', address: '12 rue Petit', city: 'Paris 19e', postal_code: '75019', logo_url: null, commerce_type: 'Boucherie' },
    },
    associations: { name: 'Hessed Avraham' },
  },
  {
    id: 'mock-don-002-aabb-ccdd-eeff-112233',
    basket_id: 'b9',
    commerce_id: 'mock-commerce-3',
    user_id: 'demo',
    amount_paid: 8.00,
    status: 'paid',
    is_donation: true,
    qr_code_token: null,
    created_at: new Date(Date.now() - 86400_000).toISOString(),
    baskets: {
      type: 'parve',
      pickup_start: new Date(new Date().setHours(12, 0)).toISOString(),
      pickup_end: new Date(new Date().setHours(14, 0)).toISOString(),
      original_price: 18.0,
      sold_price: 8.00,
      description: 'Fruits et légumes pour association',
      is_donation: true,
      commerces: { name: 'Supermarché Hatov', address: '22 rue du Gal Leclerc', city: 'Créteil', postal_code: '94000', logo_url: null, commerce_type: 'Supermarché' },
    },
    associations: { name: 'Beth Habad Créteil' },
  },
];
